### PR TITLE
Added CodeActionProvider with support for initialize field from ctor

### PR DESCRIPTION
**Pull request by simsod**

### CODE REVIEW

**Comment by jchannon** [comment]
Nice, will take a look when I have 2 mins

**Comment by jchannon** [comment]
Looks like you can end up with the below if you tell it to initialize field. Doesn't add the readonly field more than once but does in the ctor:

```
 public class newclass
    {
        private readonly IFred _fred;
        private readonly IJeff _keff;
        public newclass (IFred fred, IJeff keff)
        {
            _fred = fred;
            _fred = fred;
            _keff = keff;
            _fred = fred;
          
        }
    }
```

**Comment by jchannon** [comment]
Personal preference but could we have the below instead of underscores?

this.x = x

**Comment by simsod** [comment]
I´ll fix the multiple assignment of the private field. The code-action wont even be available if it already exist.

I´ll also add a setting for private memberfield prefix. As you say it´s a matter of preference so a setting seems appropriate.

**Comment by jchannon** [comment]
I think this needs the packages.json changes to include the default configuration options?

**Comment by jchannon** [comment]
Awesome! Thanks ❤️

**Pull request merged**
